//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VaccineCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta vacina protege contra a tuberculose. Esta vacina deve ser aplicada no recém-nascido preferencialmente ainda na maternidade.
        ///A vacina quase sempre deixa uma cicatriz característica, com até 1 cm de diâmetro, no local em que foi aplicada. Essa reação é esperada! A marca pode demorar até 6 meses para começas a aparecer.
        ///.
        /// </summary>
        internal static string BCG {
            get {
                return ResourceManager.GetString("BCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doençca infecciosa causada por um vírus e transmitida por mosquito. 
        ///Os principais sintomas são febre, calafrios, náusea, fraqueza. Os casos graves evoluem com icterícia (cor amarela da pele e olhos) quando afeta o fígado, hemorragia e morte em muitos casos (20% a 50% dos que desenvolvem a forma grave..
        /// </summary>
        internal static string Febre_Amarela {
            get {
                return ResourceManager.GetString("Febre_Amarela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Influenza ou Gripe é uma infecção aguda do sistema respiratório, ocasionada pelo vírus influenza, com elevado potencial de transmissão.
        ///Para 2018, a Organização Mundial da Saúde definiu a composição da vacina com duas cepas de influenza A (H1N1 e H3N2) e uma linhagem de influenza B..
        /// </summary>
        internal static string Gripe {
            get {
                return ResourceManager.GetString("Gripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepatite A é uma doença infecciosa aguda causada pelo vírus VHA. A transmisssão é por falta de higiênie ou falta de saneamento básico. 
        ///Em geral a pessoa não apresenta sintomas sérios. Porém, em alguns casos, porém a infecção causar sintomas clássicos como febre, dores musculares e náuseas. Quando há complicações, o fígado é afetado causando  icterícia (cor amarela da pele e olhos) e muito raramente, hepatite fulminante..
        /// </summary>
        internal static string Hepatite_A {
            get {
                return ResourceManager.GetString("Hepatite_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Hepatite B é uma doença grave que é causada por um vírus que prefere se instalar no fígado causando a sua inflamação. Em alguns casos pode haver complicações e em poucos casos pode causar morte.
        ///A primeira dose deve ser aplicada nas primeiras 12 horas de vida. A dose deve ser repetida com 2 meses e 6 meses.
        ///Se usar formas combinadas de vacina, pode-se usar o esquema de 4 aplicações: ao nascer (vacina única), 3x  DTPw-HB-Hib ou DTPa--HB-VIP-Hib.
        /// </summary>
        internal static string HEPATITE_B {
            get {
                return ResourceManager.GetString("HEPATITE_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vacina Haemophilus Influenzae B (Hib) protege contra uma bactéria que causa infecção que pode ser espalhar por diversas partes do corpo. As complicações podem causar pneumonia, meningite entre outras.
        ///Esta vacina deve ser tomada em 4 doses: 2 meses, 4 meses, 6 meses e reforço aos 15 meses. Os postos de saúde não fornecem o reforço, infelizmente..
        /// </summary>
        internal static string Hib {
            get {
                return ResourceManager.GetString("Hib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacina para o meningococo B bem menos frequente que o C que também causa meningite meningocócica.
        ///Representa 20% dos casos registrados..
        /// </summary>
        internal static string Meningocócica_B {
            get {
                return ResourceManager.GetString("Meningocócica_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meningite meningocócica (infecção das membranas que recobrem o cérebro) certamente está entre as doenças imunopreveníveis mais temidas. Ela é causada pela bactéria Neisseria meningitidis (meningococo) e é mais grave quando atinge a corrente sanguínea, provocando infecção generalizada (meningococcemia).
        ///Cinco tipos (sorogrupos) de meningococo causam a maioria dos casos de DM. São eles: A, B, C, W e Y. O meningococo C é o mais comum e foi responsável por 70% dos casos da doença.
        ///As vacinas deste grupo não pre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Meningocócicas_Conjugadas {
            get {
                return ResourceManager.GetString("Meningocócicas_Conjugadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vacina ajuda a proteger as crianças das doenças causadas pela bactéria Streptococcus pneumoniae. Entre elas estão: meningite, pneumonia, otite média aguda, sinusite e bacteremia..
        /// </summary>
        internal static string Pneumocócica_Conjugada {
            get {
                return ResourceManager.GetString("Pneumocócica_Conjugada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Poliomielite é uma doença muito grave causada pelo  Poliovírus. Nos casos mais graves, o poliovírus destrói as células nervosas da medula espinhal causando paralisia.
        ///As 3 primeiras doses devem ser VIP (vacina inativada poliomielite) injetável. As doses de reforço podem ser as famosas gotinhas - VOP (vacina oral poliomielite) mas recomenda-se manter a VIP.
        ///.
        /// </summary>
        internal static string Poliomielite {
            get {
                return ResourceManager.GetString("Poliomielite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O rotavírus causa diarreia grave, frequentemente acompanhada de febre e vômitos. É, hoje, considerado um dos mais importantes agentes causadores de gastroenterites e óbitos em crianças menores de 5 anos, em todo o mundo.
        ///Temos 2 tipos de vacinas ambas via oral (gotinha): 
        ///	1. Vacina oral monovalente (VRH1): tem um tipo de vírus enfraquecido. Se esta vacina for usada, duas doses devem ser aplicadas nos bebês.
        ///	2. Vacina oral atenuada pentavalente (VR5): é formada por cinco tipos de rotavírus vivos “enfraquec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rotavírus {
            get {
                return ResourceManager.GetString("Rotavírus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As vacinas tríplices bacterianas protegem o bebê contra difteria, coqueluche e tétano.
        ///Temos 3 tipos de vacinas diferentes 
        ///	1. DTPw que é feita a partir de células inteiras da bactéria.  
        ///	2. DTPa não é feita com as células inteiras, mas só com proteínas. Elas causam menos efeitos colaterais, mas só está disponível nas clínicas particulares. 
        ///	3. A vacina dTpa é a formulação para adultos.
        ///Com o aumento da coqueluche no Brasil nos últimos anos é importante que ela seja aplicada nas gestantes (entre 27 a 36  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tríplice_Bacteriana {
            get {
                return ResourceManager.GetString("Tríplice_Bacteriana", resourceCulture);
            }
        }
    }
}
